#ifndef NUMERIC_REPLIES
# define NUMERIC_REPLIES

# define RPL_REGISTERUSER "REGISTER USER"
# define RPL_WELCOMEMESSAGE "WELCOME MESSAGE"
# define RPL_MOTD "MOTD"
# define RPL_PASS "PASS"
# define RPL_NICK "NICK"
# define RPL_USER "USER"
# define RPL_MODE "MODE"
# define RPL_HOST "HOST"
# define RPL_OTHERSERVER "OTHER SERVER"
# define RPL_SERVER "SERVER"
# define RPL_NICKBROADCAST "NICK BROADCAST"
# define RPL_USERBROADCAST "USER BROADCAST"
# define RPL_USERMODEBROADCAST "MODE BROADCAST"
# define RPL_SERVERBROADCAST "SERVER BROADCAST"
# define RPL_KILL "KILL"
# define RPL_SQUIT "SQUIT"
# define RPL_QUIT "QUIT"
# define RPL_SQUITBROADCAST "SQUIT BROADCAST"
# define RPL_QUITBROADCAST "QUIT BROADCAST"

# define ERR_PASSUNAUTHORIE "PASS UNAUTHORIE"
# define ERR_ERRONEUSUSERNAME "ERRONEUS USER NAME"
# define ERR_PREFIX "PREFIX ERROR"

# define RPL_WELCOME "001"
# define RPL_YOURHOST "002"
# define RPL_CREATED "003"
# define RPL_MYINFO "004"
# define RPL_BOUNCE "005"

# define RPL_TRACELINK "200"
# define RPL_TRACEOPER "204"
# define RPL_TRACEUSER "205"
# define RPL_TRACESERVER "206"
# define RPL_TRACEEND "262"

# define RPL_STATSLINKINFO "211"
# define RPL_STATSCOMMANDS "212"
# define RPL_STATSCLINE "213"
# define RPL_STATSNLINE "214"
# define RPL_STATSILINE "215"
# define RPL_STATSKLINE "216"
# define RPL_STATSYLINE "218"
# define RPL_ENDOFSTATS "219"
# define RPL_STATSLLINE "241"
# define RPL_STATSUPTIME "242"
# define RPL_STATSOLINE "243"
# define RPL_STATSHLINE "244"

# define STATS_L "STATS_l"
# define STATS_M "STATS_m"
# define STATS_O "STATS_o"
# define STATS_U "STATS_u"



# define RPL_LUSERCLIENT "251"
# define RPL_LUSERCHANNELS "254"
# define RPL_LUSERME "255"

# define RPL_ADMINME "256"
# define RPL_ADMINLOC1 "257"
# define RPL_ADMINLOC2 "258"
# define RPL_ADMINEMAIL "259"

# define RPL_LISTSTART "321"
# define RPL_LIST "322"
# define RPL_LISTEND "323"

# define RPL_NOTOPIC "331"
# define RPL_TOPIC "332"
# define RPL_TOPICWHOTIME "333"

# define RPL_INVITING "341"

# define RPL_INVITELIST "346"
# define RPL_ENDOFINVITELIST "347"

# define RPL_EXCEPTLIST "348"
# define RPL_ENDOFEXCEPTLIST "349"

# define RPL_VERSION "351"
# define RPL_NAMREPLY "353"

# define RPL_LINKS "364"
# define RPL_ENDOFLINKS "365"
# define RPL_ENDOFNAMES "366"

# define RPL_BANLIST "367"
# define RPL_ENDOFBANLIST "368"


# define RPL_INFO "371"
# define RPL_ENDOFINFO "374"

# define RPL_MOTDCONTENT "372"
# define RPL_MOTDSTART "375"
# define RPL_ENDOFMOTD "376"

# define RPL_TIME "391"

# define ERR_NOSUCHNICK "401"
# define ERR_NOSUCHSERVER "402"
# define ERR_NOSUCHCHANNEL "403"
# define ERR_CANNOTSENDTOCHAN "404"
# define ERR_TOOMANYCHANNELS "405"
# define ERR_WASNOSUCHNICK "406"
# define ERR_TOOMANYTARGETS "407"
# define ERR_NOORIGIN "409"
# define ERR_NORECIPIENT "411"
# define ERR_NOTEXTTOSEND "412"
# define ERR_NOTOPLEVEL "413"
# define ERR_WILDTOPLEVEL "414"
# define ERR_UNKNOWNCOMMAND "421"
# define ERR_NOMOTD "422"
# define ERR_NOADMININFO "423"
# define ERR_FILEERROR "424"
# define ERR_NONICKNAMEGIVEN "431"
# define ERR_ERRONEUSNICKNAME "432"
# define ERR_NICKNAMEINUSE "433"
# define ERR_NICKCOLLISION "436"
# define ERR_USERNOTINCHANNEL "441"
# define ERR_NOTONCHANNEL "442"
# define ERR_USERONCHANNEL "443"
# define ERR_NOLOGIN "444"
# define ERR_SUMMONDISABLED "445"
# define ERR_USERSDISABLED "446"
# define ERR_NOTREGISTERED "451"
# define ERR_NEEDMOREPARAMS "461"
# define ERR_ALREADYREGISTRED "462"
# define ERR_NOPERMFORHOST "463"
# define ERR_PASSWDMISMATCH "464"

# define ERR_UNKNOWNMODE "472"
# define ERR_INVITEONLYCAHN "473"
# define ERR_BANNEDFROMCHAN "474"
# define ERR_BADCHANNELKEY "475"

# define ERR_CHANOPRIVSNEEDED "482"
# define ERR_CANTKILLSERVER "483"

#endif
